# Generated by Django 3.1.1 on 2021-11-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211126_1923'),
        ('account', '0006_auto_20211126_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercategory', to='pages.category'),
        ),
    ]
