# Generated by Django 3.1.1 on 2021-11-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211126_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
