# Generated by Django 3.1.1 on 2021-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
