# Generated by Django 3.1.1 on 2021-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_addwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addwork',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addwork',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
