# Generated by Django 3.1.1 on 2021-12-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_commentsblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsblog',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentblog', to='pages.blog'),
        ),
    ]
