# Generated by Django 3.1.1 on 2021-12-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_commentsblog_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='commentsblog',
            options={'ordering': ('-date',)},
        ),
    ]
