# Generated by Django 3.1.1 on 2021-12-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20211231_2213'),
        ('community', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
