# Generated by Django 3.1.1 on 2021-12-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20211231_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('-date',)},
        ),
    ]
