# Generated by Django 3.1.1 on 2022-01-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20211231_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={},
        ),
    ]
