# Generated by Django 3.1.1 on 2022-01-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20220103_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='hide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
