# Generated by Django 3.1.1 on 2022-01-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_messages_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='hide_id',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
