# Generated by Django 3.1.1 on 2022-01-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_messages_hide_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='hide_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
